/**
 * Writes docs/claims-to-verify.md — every `claimsToVerify` line of every
 * registered evergreen page, grouped by door, as one checklist for the founder.
 * The content files stay the source of truth: a wrong claim is a one-line edit
 * in `src/content/evergreen/<file>.ts`, then re-run this.
 *
 *   npm run docs:claims            # rewrite the file
 *   npm run docs:claims -- --check # exit 1 if the file is out of date
 *
 * Pure: no database, no network.
 */
import fs from "node:fs";
import path from "node:path";
import { EVERGREEN_PAGES, evergreenWordCount } from "../src/content/evergreen";
import { VERTICALS } from "../src/config/verticals";

const OUT = path.join(process.cwd(), "docs", "claims-to-verify.md");
const OPERATIONAL = /^operational promise/i;

function hostOf(key: string): string {
  const hit = Object.entries(VERTICALS).find(([, v]) => v.key === key);
  return hit ? hit[0] : key;
}

const byDoor = new Map<string, typeof EVERGREEN_PAGES[number][]>();
for (const p of EVERGREEN_PAGES) {
  const host = hostOf(p.door);
  byDoor.set(host, [...(byDoor.get(host) ?? []), p]);
}

const total = EVERGREEN_PAGES.reduce((n, p) => n + p.claimsToVerify.length, 0);
const promises = EVERGREEN_PAGES.reduce(
  (n, p) => n + p.claimsToVerify.filter((c) => OPERATIONAL.test(c)).length,
  0,
);

const lines: string[] = [
  "# Evergreen pages — claims to verify",
  "",
  "<!-- Generated by `npm run docs:claims` from src/content/evergreen. Do not edit by hand:",
  "     fix the claim in the content file and re-run. -->",
  "",
  `${EVERGREEN_PAGES.length} pages, ${total} claims (${promises} of them are operational promises about how the team answers a brief, not facts about Paraguay).`,
  "",
  "How to use: tick a claim you know is true. If one is wrong or you are unsure, change or delete the sentence in the file named under the page heading, and the claim line with it. Nothing on the site has been checked against a source by an agent.",
  "",
];

for (const [host, pages] of [...byDoor.entries()].sort()) {
  lines.push(`## ${host}`, "");
  for (const p of pages) {
    const file = `src/content/evergreen/${p.path.replace(/^\//, "").replace(/\//g, "-")}.ts`;
    lines.push(
      `### ${p.path} — "${p.keyword}" (${evergreenWordCount(p)} words)`,
      "",
      `File: \`${p.door === "en" ? file.replace("evergreen/", "evergreen/en-") : file}\``,
      "",
    );
    for (const c of p.claimsToVerify) lines.push(`- [ ] ${c}`);
    lines.push("");
  }
}

const next = lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";

if (process.argv.includes("--check")) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (cur !== next) {
    console.error("docs/claims-to-verify.md is out of date — run: npm run docs:claims");
    process.exit(1);
  }
  console.log("docs/claims-to-verify.md is up to date");
} else {
  fs.writeFileSync(OUT, next);
  console.log(`wrote ${path.relative(process.cwd(), OUT)}: ${EVERGREEN_PAGES.length} pages, ${total} claims`);
}
